---
- hosts: all
  become: true
  tasks:

  - name: install apache2 and php 
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
      autoremove: yes
  

